trainer: nerv_enc_trainer_full_res_weight_saver_overlap

test_dataset:
  name: vidrec_dataset_patch_tubelet_inference_lazy_uvg
  args: {root_path: data/dataset_meta, frame_num: $frame_num$, 
    cls_vid_num: '-1_-1', crop_size: $input_size$, tubelet_size: $tubelet_size$}
  csv_paths: {hevc_e: hevc_class_e.csv}
  frames: {input: $eval_frames$, output: 'none'}
  loader:
    batch_size: $batch_size$
    num_workers: $num_workers$

eval_full_res_dataset:
  name: vidrec_dataset_full_res_overlapping_patches_single_video_uvg
  args: {frame_num: $frame_num$, crop_size: $input_size$, tubelet_size: $tubelet_size$}
  frames: {input: $eval_frames$, output: 'none'}
  loader:
    batch_size: $batch_size$
    num_workers: $num_workers$

dump_ckt: 'no'
dump_pred: 'no'
dump_video: 'no'

generate_from_single_frame: false

eval_residuals: false

eval_model: checkpoints/patch_tubelet/320x160_finetuned_patch/epoch-last.pth
save_path: save/patch_preds_overlap/patch_preds_hevc_e_480p
eval_same_model: true
eval_saver: null
quant_bit: none
encoding_type: none
eval_weights_residuals: false
eval_csv_prefix: ''

save_weights_no_quant: no
save_weights_quant: no
residuals_type: from_prev # direct weights for baseline, from_prev residuals for Patch-Tubelet and TeCoNeRV
target_vid: johnny
overlap_h: 20
overlap_w: 20
